### ISSUE TITLE
Play Audio/Sound

### ISSUE THREAD

**Issue by akumamg** [openlumi/lumimqtt#4]
Can you add ability to play audio and streaming ?.
Like ZESP

**Comment by devbis** [comment]
It is not supported by Homeassistant autodiscovery in any way. So it is not the top priority right now. 
You may want to check a third-party project that offers this functionality:
https://github.com/Beetle-II/lumi

**Comment by muniter** [comment]
Hey @devbis I was looking for alternatives and just installed mpd in the lumi with the supported openwrt [package](https://openwrt.org/packages/pkgdata/mpd-full) and using the [mpd integration in HA](https://www.home-assistant.io/integrations/mpd/) in was almost plug and play. Just had to change the "address" value in `/etc/mpd.conf` to my lumi ip address.

This now allows text to speech, or pretty much anything.

**Comment by mrprerfect** [comment]
Hi @muniter  could you please describe this solution a little more? I have installed mpd on GW set what you mentioned, but there is no sound at all. I tried to play something with mpc directly on GW but no luck. How to configure `/etc/mpd.conf` in order to play something on local speaker?
Thanks in advance

**Comment by muniter** [comment]
Hello @mrprerfect I had some small issues as the comment above describe. First I had to modify the audio output section in `/etc/mpd.conf` to:
```
audio_output {
        type            "alsa"
        name            "My ALSA Device"
        device          "hw:0,0"        # optional
        mixer_type      "software"      # optional
##      mixer_device    "default"       # optional
##      mixer_control   "PCM"           # optional
##      mixer_index     "0"             # optional
}
```
I also went into `alsamixer` command and checked that things weren't muted.

And I had to modify the init file since it was a kind of buggy causing mpd to not always start on boot (I added the respawn parameter), to the following.

`/etc/init.d/mpd`

```
#!/bin/sh /etc/rc.common
# Copyright (C) 2007-2014 OpenWrt.org

START=93

USE_PROCD=1

PROG=/usr/bin/mpd
CONFIGFILE=/etc/mpd.conf
NICEPRIO=-10

#TODO: Add uci config - nice, config

depend() {
        need network
}

start_service() {
        local pld lport

        #create mpd directories from config
        pld=$(grep ^playlist_directory "$CONFIGFILE" | cut -d "\"" -f 2 | sed "s/~/\/root/g")
        [ -d "$pld" ] || mkdir -m 0755 -p /tmp/mpd

        lport=$(grep ^port "$CONFIGFILE" | cut -d "\"" -f 2)
        [ -z "$lport" ] && lport=6600

        procd_open_instance
        procd_add_mdns "mpd" "tcp" "$lport"
        procd_set_param command "$PROG" --no-daemon "$CONFIGFILE"
        procd_set_param stderr 1
        procd_set_param respawn
        # Give MPD some real-time priority
        procd_set_param nice "$NICEPRIO"
        procd_close_instance
}

reload_service() {
        procd_send_signal "$PROG"
}
```
Then I just used the mpd integration in home assistant. Hope it works.

**Comment by mrprerfect** [comment]
Hi @muniter  Thank you very much for the info! now everything is working fine..

**Comment by devbis** [comment]
You can implement playing sound with custom commands with MQTT topics: https://github.com/openlumi/lumimqtt#custom-commands.
Although, the recommended way is still using the HA MPD integration.

Closing the task.

**Comment by cihantok** [comment]
@muniter and @mrprerfect thanks.
